### PR TITLE
Reformat example yaml

### PR DESCRIPTION
**Pull request by biox**
* original didn't work out of the box - this one does.

Also worth noting, I'm very interested in this project and just started learning Go - you may see commits from me in the future.

I figure this is safe enough to merge straight into master.

### CODE REVIEW

**Comment by DanielOaks** [comment]
Heya, thanks for the PR! Hmm, this change does look very strange though, because of the indent changes it looks like `listeners` (and the rest of the config) may be underneath the `storage` key from the looks of it.

I wonder whether the default config is a bit broken because of the logging changes, and this change simply means that the config parser is just ignoring all those sections as broken.

I'll dig into this, see what's up and then give you a yell, thanks very much for the contribution though – there's definitely some trouble to work around here. And all good, if there's anything you wanna chat about you can always pop onto our channel to say hi :)

P.S. as a little note, it looks like your commit isn't using any email address, or at least not any recognised by Github. If you run this on your machine (or otherwise set the 'email' option in the git you're using), and set the email address to the same one you use for Github, it'll link your commits to your account:
```
git config --global user.email "email@example.com"
```

**Comment by DanielOaks** [comment]
As a note, there's some changes on the [`devel`](https://github.com/goshuirc/bnc/tree/devel) branch, which fix some broken stuff (and I've been meaning to merge back into master). Nothing to worry about but interesting if you're looking at stuff working / being broken out of the box :)

**Comment by biox** [comment]
> this change does look very strange though, because of the indent changes it looks like listeners (and the rest of the config) may be underneath the storage key from the looks of it.

Whoops! Corrected.

> I wonder whether the default config is a bit broken because of the logging changes, and this change simply means that the config parser is just ignoring all those sections as broken.

Maybe. It looks like we're using the same pattern to look up both the storage values and logging values - `map[string]string`. That information is based on the struct in lib/config.go:

```go
type Config struct {
	Bouncer struct {
		Storage      map[string]string
		Listeners    []string
		TLSListeners map[string]*TLSListenConfig `yaml:"tls-listeners"`
		Logging      map[string]string
	}
}
```

> And all good, if there's anything you wanna chat about you can always pop onto our channel to say hi :)

I will! 

> as a little note, it looks like your commit isn't using any email address, or at least not any recognised by Github

Another whoops! This has been corrected. 👍 

> As a note, there's some changes on the devel branch, which fix some broken stuff (and I've been meaning to merge back into master).

I love broken stuff. If you're willing to deal with PRs that aren't ideal right away I'd love to help out with making/documenting this bouncer - it's something that I'd love to have for personal use. Current bouncers are way too feature-heavy and bloated IMO (ZNC being a good example). I don't want to lug a web interface around - a yaml file and a binary is all one should need ;)

Thanks for being so welcoming!

**Comment by DanielOaks** [comment]
Aha all good, glad to help out and take a look at PRs that take a while to stabilise! In terms of this project, I'd say @prawnsalad's more interested in this being useful for something like KiwiIRC, where my focus is in making sure it stays pretty small and good for home use.

**Comment by DanielOaks** [comment]
I think that fa595b3055798aa0d381c38e69a0eb529975e800 should fix this up from the looks of it – default config hadn't been updated to work with the new config loading format :)

**Comment by biox** [comment]
@DanielOaks yup, that commit resolved the 'first try failure' I was having. 👍

**Comment by DanielOaks** [comment]
Whoo, awesome! In that case I'll close this PR, but definitely interested in looking at and merging in future ones. Thanks again for pointing out the issues here!

**Pull request closed without merging**
