### PR TITLE
Send NAMES upstream when dumping channels as some clients expect NAME…

### PR DESCRIPTION
**Pull request by prawnsalad**
…S to be automatic

### CODE REVIEW

**Comment by DanielOaks** [comment]
Note to self: take a look at #10 as well with this. I think that this change looks correct – getting names sent to listeners makes sense (could manually construct the NAMES messages ourselves if we really wanted to though) – but because of #10 we're likely not joining the channels as we're supposed to anyways.

**Comment by prawnsalad** [comment]
Constructing the NAMES messages ourselves would involve keeping track of user lists which could 1) get memory hungry if there are many BNC users, and 2) be a lot more work than just sending NAMES upstream which does the same job.

**Comment by DanielOaks** [comment]
Makes sense, I'll just leave it as it is here for now in that case

**Comment by DanielOaks** [comment]
Merged into master, thanks!

**Pull request closed without merging**
